module.exports = {
  plugins: ['prettier-plugin-tailwindcss', '@ianvs/prettier-plugin-sort-imports'],
  printWidth: 120,
  singleQuote: true,
  bracketSpacing: true,
  endOfLine: 'lf',
  bracketSpacing: true,
  importOrderCaseInsensitive: true,
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  importOrder: [
    '^radix-ui/(.*)$',
    '^(next/(.*)$)|^(next$)',
    '^next-.+$',
    '^(react/(.*)$)|^(react$)',
    '^react-.+$',
    '<THIRD_PARTY_MODULES>',
    '',
    '<BUILTIN_MODULES>',
    '',
    '^[@/]',
    '',
    '^../(.*)$',
    '',
    '^[./]',
  ],
};
